# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "prepare"
  - "test"
  - "build"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "kostis-codefresh/public-tag-checker"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github-1"
    stage: "clone"

  build_deps:
    title: "Building Deps Docker image"
    type: "build"
    image_name: "public-tag-checker"
    working_directory: "${{clone}}"
    tag: deps
    dockerfile: "Dockerfile"
    target: build_base
    disable_push: true
    stage: "prepare"

  test:
    title: "Unit Test"
    type: "freestyle" # Run any command
    image: ${{build_deps}}
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "CGO_ENABLED=0 go test -v -run=Unit"
    stage: "test"
    
  build_app:
    title: "Building App Docker image"
    type: "build"
    image_name: "public-tag-checker"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"    

