# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "prepare"
  - "test"
  - "build"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "kostis-codefresh/public-tag-checker"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github-1"
    stage: "prepare"

  build_deps:
    title: "Building Deps Docker image"
    type: "build"
    image_name: "public-tag-checker"
    working_directory: "${{clone}}"
    tag: deps
    dockerfile: "Dockerfile"
    target: build_base
    disable_push: true
    stage: "prepare"

  unit_test:
    title: "Unit Test"
    type: "freestyle" 
    image: ${{build_deps}}
    working_directory: "${{clone}}" 
    commands:
      - "CGO_ENABLED=0 go test -v -run=Unit"
    stage: "test"
    
  integration_tests:
    title: "Integration Test"
    type: "freestyle" 
    image: ${{build_deps}}
    working_directory: "${{clone}}" 
    commands:
      - "CGO_ENABLED=0 go test -v -run=Integration"
    stage: "test"    
    
  build_app:
    title: "Building App Docker image"
    type: "build"
    image_name: "kkapelon/public-tag-checker"
    working_directory: "${{clone}}"
    tag: latest 
    dockerfile: "Dockerfile"
    registry: dockerhub
    stage: "build"   
  
  create_plugin:
    title: "Create plugin"
    type: "freestyle" 
    image: codefresh/cli
    working_directory: "${{clone}}" 
    commands:
      - "codefresh replace step-type kostis-codefresh/newest-dockerhub-tag -f find-newest-tag.yml"
    stage: "deploy"     


